### ISSUE TITLE
No Segments

### ISSUE THREAD

**Issue by Hgit007** [stultus/mp4-to-mpegdash-py#16]
Hello,

Thanks for your sharing. I am interested to use this tool. But after running, I can only get the *.mpd file and the *init.mp4 file. Could you please help me  figure out how to save segments for every quality level? This is the example link. [http://ftp.itec.aau.at/datasets/DASHDataset2014/BigBuckBunny/1sec/](url)

Thank you.

Best

**Comment by stultus** [comment]
Hello @Hgit007 ,
Thanks for your interest.  The segments are packaged into a single mp4 file using `MP4Box`.  
The segments are there, but in a single file,  which is easier to maintain.
